name: PackReleaseOnWindows10

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          # A directory to store and save the cache
          path: .githubActions/cache
          # An explicit key for restoring and saving the cache
          key: windows-latest-pack-release

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: |
          python -m pip install pyinstaller

      - name: Compiler pyside6 resource
        run: pyside6-rcc resources\resources.qrc -o packages\resources.py

      - name: Make release
        run: |
          pyinstaller --noconfirm --onedir --windowed --icon "resources/raw/icon.ico" --clean --workpath "release/pyinstaller/work/" --distpath "release/pyinstaller/dist/" "main.py"
          cd "release\pyinstaller\dist\main\"
          ren main.exe OMDownloader.exe

      - name: Inno Build
        run: python devTools\innoScriptBuilder.py

      - name: Inno Pack
        uses: nadeemjazmawe/inno-setup-action-cli@v6.0.5
        with:
          filepath: './devTools/exePack/installerPack/innoScript.iss'

      - name: Upload Portable
        uses: actions/upload-artifact@v3
        with:
          name: auto build portable zip
          path: release/pyinstaller/dist/main

      - name: Upload Installer
        uses: actions/upload-artifact@v3
        with:
          name: auto build installer
          path: release/nanoInstaller/OMDownloader.exe
